# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ros_messages.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'ros_messages.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12ros_messages.proto\x12\x0cros_messages\"O\n\nSensorData\x12\x11\n\tsensor_id\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x01\x12\x0c\n\x04unit\x18\x03 \x01(\t\x12\x11\n\ttimestamp\x18\x04 \x01(\x03\"T\n\tRobotPose\x12\t\n\x01x\x18\x01 \x01(\x01\x12\t\n\x01y\x18\x02 \x01(\x01\x12\t\n\x01z\x18\x03 \x01(\x01\x12\x13\n\x0borientation\x18\x04 \x01(\x01\x12\x11\n\ttimestamp\x18\x05 \x01(\x03\"]\n\tImageData\x12\r\n\x05width\x18\x01 \x01(\x05\x12\x0e\n\x06height\x18\x02 \x01(\x05\x12\x10\n\x08\x65ncoding\x18\x03 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x04 \x01(\x0c\x12\x11\n\ttimestamp\x18\x05 \x01(\x03\"2\n\x0eStatusResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2\xfd\x01\n\tROSBridge\x12P\n\x10StreamSensorData\x12\x18.ros_messages.SensorData\x1a\x1c.ros_messages.StatusResponse\"\x00(\x01\x30\x01\x12N\n\x0fStreamRobotPose\x12\x17.ros_messages.RobotPose\x1a\x1c.ros_messages.StatusResponse\"\x00(\x01\x30\x01\x12N\n\x0fStreamImageData\x12\x17.ros_messages.ImageData\x1a\x1c.ros_messages.StatusResponse\"\x00(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ros_messages_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SENSORDATA']._serialized_start=36
  _globals['_SENSORDATA']._serialized_end=115
  _globals['_ROBOTPOSE']._serialized_start=117
  _globals['_ROBOTPOSE']._serialized_end=201
  _globals['_IMAGEDATA']._serialized_start=203
  _globals['_IMAGEDATA']._serialized_end=296
  _globals['_STATUSRESPONSE']._serialized_start=298
  _globals['_STATUSRESPONSE']._serialized_end=348
  _globals['_ROSBRIDGE']._serialized_start=351
  _globals['_ROSBRIDGE']._serialized_end=604
# @@protoc_insertion_point(module_scope)
